version: '3'
services:
  nodejs:
    image: node:18.18.2-alpine3.18
    command: ['tail', '-f', '/dev/null']
    working_dir: /app
    volumes:
      - .:/app
    user: 'node'
    ports:
      - '3000:3000'
      - '35729:35729'

  backstopjs:
    image: ghcr.io/health-education-england/run-backstopjs-regression-tests:main
    volumes:
      - ./tests/backstop:/app/src/backstop
      - ./public:/app/src/public

  playwright:
    image: mcr.microsoft.com/playwright:v1.36.1-jammy
    working_dir: /app
    volumes:
      - .:/app
