version: '3'
services:
  backstopjs:
    image: ghcr.io/health-education-england/run-backstopjs-regression-tests:main
    volumes:
      - ./tests/backstop:/app/src/backstop
      - ./public:/app/src/public

  playwright:
    image: mcr.microsoft.com/playwright:v1.35.1-jammy
    volumes:
      - .:/app
