name: Build, test, commit and deploy

# Only run workflow when committing directly to master, release branches or when within a PR.
on:
  push:
    branches:
      - master
      - develop
      - release/*
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  # Build prototype dependencies, assets and templates.
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-optional

      # This builds the assets with the correct '/hee-prototypes/' basePath for Github Pages.
      - name: Build assets (for Github Pages deployment)
        run: npm run build:prod

      - name: Upload Github Pages build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: public/**
          retention-days: 1

      # Builds assets for pipeline tests operations (no basepath).
      - name: Build assets (for local tests)
        run: npm run build

      # Share built assets between jobs.
      - name: Upload testing build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: assets-tests
          path: public/**
          retention-days: 1

  # Prepare the "dist" directory use by GitHub pages to serve prototype.
  bundle:
    name: Bundle and Commit
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      # Copy assets from "Build" step into "dist/" directory.
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: dist/

      # Debugging step to display ./dist directory contents in GitHub action logs.
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist/

      # Commit any changes to ./dist directory..
      - name: Commit bundled dist changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Github Actions] - Bundled assets for build number: ${{ github.run_number }}"

  # Run backstopjs regression tests only when in PR.
  test_backstopjs:
    if: github.event_name == 'pull_request'
    name: 'Run tests: BackstopJS'
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      # Download assets from "Build" step into "public/" directory.
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets-tests
          path: public

      # Docker image: ghcr.io/health-education-england/run-backstopjs-regression-tests:main
      - name: Pull HEE backstopjs docker image
        run: docker-compose pull

      # Run backstopjs tests.
      - name: Run backstopjs tests
        run: docker-compose run backstopjs npm run backstop:test

      # Upload html report as an asset
      - name: Upload backstop report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: backstop_report
          path: tests/backstop/backstop_data/**
          retention-days: 1

      # Upload backstop config as asset for debugging.
      - name: Upload generated backstop config
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: backstop_generated_config
          path: tests/backstop/config/backstop.json
          retention-days: 1

  # Run playwright integration tests only when in PR.
  test_playwright:
    if: github.event_name == 'pull_request'
    name: 'Run tests: Playwright'
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      # Download assets from "Build" step into "public/" directory.
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets-tests
          path: public

      # Docker image: mcr.microsoft.com/playwright:v1.35.1-jammy
      - name: Pull playwright docker image
        run: docker-compose pull

      # Run playwright tests.
      - name: Run playwright tests
        run: npm run playwright:test

      # Upload html report as an asset
      - name: Upload backstop report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: playwright_report
          path: tests/playwright/report/**
          retention-days: 1

  # Runs the release job if we're on "develop" to deploy our latest build to GitHub Pages.
  deploy:
    if: github.ref == 'refs/heads/develop'
    name: Deploy
    needs: bundle
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #  Ensures that we use the latest commit from step: "Commit bundled dist changes" above.
      - name: Fetch latest commit from bundle step
        run: git pull --no-rebase

      # Deploys and updates GitHub Pages.
      - name: Deploy GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: dist
