name: Deploy to GitHub Pages branch

on:
  workflow_run:
    workflows:
      - "Build and Commit"
    branches:
      - "develop"
    types:
      - completed

jobs:
  release:
    # Only run the release job if "Build and Test" workflow completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploys and updates GitHub Pages.
      - name: Deploy GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: dist
