name: Release

on:
  workflow_run:
    workflows:
      - "Build and Test"
    branches:
      - master
    types:
      - completed

jobs:
  release:
    # Only run the release job if "Build and Test" workflow completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      # Copy assets from "Build" step into "dist/" directory.
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: dist/

      # Deploys and updates GitHub Pages.
      - name: Deploy GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: dist
