name: Run tests

# Run workflow on opening a new PR or updating an existing PR.
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Download build assets
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      # Wait for Build operation to finish from build_commit_deploy workflow.
      - name: Wait for build operation to complete
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Build'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      # Download assets from "Build" step into "public/" directory.
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: public/

      # Debugging step to display ./dist directory contents in GitHub action logs.
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: public/

  backstopjs:
    name: Run backstopjs tests
    runs-on: ubuntu-latest

    # Docker image - https://github.com/Health-Education-England/run-backstopjs-regression-tests
    container:
      image: ghcr.io/health-education-england/run-backstopjs-regression-tests:main

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      # Download assets from "Build" step into "public/" directory.
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: public/

      # Debugging step to display ./public directory contents in GitHub action logs.
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: public/

      # Run backstopjs tests.
      - name: Run backstopjs tests
        run: npm run backstop:test
